#!/usr/bin/bash

fileName=`echo "$1" | gsed 's/*//'`

if [ "$filename" == "" ]
then
	ls -lt | awk '$1 ~ /^l/' | gsed 's/.\+[0-9]\{2\} \(.\+\) -> .\+/\1/'
else
	for linkId in `ls -lti | awk '$2 ~ /^l/ {print $1}'`
	do
		name=`ls -li | nawk -v linkId=$linkId '$1 == linkId' | gsed 's/.\+-> \(.\+\)/\1/' | gsed 's/*/star/'`
	
		if [ "($name)" == "($filename)" ] 
		then
			gfind -inum "$linkId" | sed s/\\\.\\\///
		fi
	done

fi
